---

- name: Install tomcat
  hosts: localhost
  become: true

  pre_tasks:

    - name: install wget
      yum: 
        name: wget
        state: present

    - name: install unzip
      yum: 
        name: unzip
        state: present

    - name: install and enable firewalld
      dnf:
        name: firewalld
        state: present

    - name: start firewalld
      service:
       name: firewalld
       state: started
       enabled: yes
      
  roles:
    
    - role: java
    - role: tomcat

...
