---

- name: Install tomcat
  hosts: localhost
  become: true

  pre_tasks:

    - name: install wget
      yum: 
        name: wget
        state: present

    - name: install unzip
      yum: 
        name: unzip
        state: present

    - name: install y enable firewalld
      dnf:
        name: firewalld
        state: present

    - name: enable firewalld
      firewalld:
        permanent: yes
        immediate: yes
        state: enabled

  roles:
    
    - role: java
    - role: tomcat

...
